# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PIL import Image,ImageQt

class Ui_Steganographie(object):

    def __init__(self):
        self.image_name = "Aucune fichier selectionnée!"
        

    def load(self):
        dlg = QFileDialog()
        dlg.setFileMode(QFileDialog.AnyFile)
        filenames = ""

        if dlg.exec_():
            filenames = dlg.selectedFiles()
            print(filenames[0])
            self.file_name_label.setText(filenames[0])

        im = Image.open(filenames[0])
        QtIm = ImageQt.ImageQt(im)
        QtIm = QtGui.QImage(QtIm)
        pix = QtGui.QPixmap.fromImage(QtIm)
        pix = pix.scaled(250,250,QtCore.Qt.KeepAspectRatio)
        self.image_container.setPixmap(pix)

    def get_input(self):
        print(self.text_container.toPlainText())

    def setupUi(self, Steganographie):
        Steganographie.setObjectName("Steganographie")
        Steganographie.resize(288, 522)
        self.image_container = QtWidgets.QLabel(Steganographie)
        self.image_container.setGeometry(QtCore.QRect(20, 50, 250, 250))
        self.image_container.setAutoFillBackground(True)
        self.image_container.setAlignment(QtCore.Qt.AlignCenter)
        self.image_container.setObjectName("image_container")


        self.hide_text = QtWidgets.QPushButton(Steganographie)
        self.hide_text.setGeometry(QtCore.QRect(10, 480, 121, 31))
        self.hide_text.setObjectName("hide_text")
        self.hide_text.clicked.connect(self.get_input)

        self.text_container = QtWidgets.QTextEdit(Steganographie)
        self.text_container.setGeometry(QtCore.QRect(10, 310, 261, 161))
        self.text_container.setObjectName("text_container")
        self.show_text = QtWidgets.QPushButton(Steganographie)
        self.show_text.setGeometry(QtCore.QRect(150, 480, 121, 31))
        self.show_text.setObjectName("show_text")
        self.widget = QtWidgets.QWidget(Steganographie)
        self.widget.setGeometry(QtCore.QRect(12, 12, 261, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name_label = QtWidgets.QLabel(self.widget)
        self.file_name_label.setObjectName("file_name_label")
        self.horizontalLayout.addWidget(self.file_name_label)


        self.load_image_btn = QtWidgets.QPushButton(self.widget)
        self.load_image_btn.setObjectName("load_image_btn")
        self.load_image_btn.clicked.connect(self.load)
        self.horizontalLayout.addWidget(self.load_image_btn)

        self.retranslateUi(Steganographie)
        QtCore.QMetaObject.connectSlotsByName(Steganographie)

    def retranslateUi(self, Steganographie):
        _translate = QtCore.QCoreApplication.translate
        Steganographie.setWindowTitle(_translate("Steganographie", "Dialog"))
        self.image_container.setText(_translate("Steganographie", "Image"))
        self.hide_text.setText(_translate("Steganographie", "Cacher dans l\'image"))
        self.show_text.setText(_translate("Steganographie", "Extraire le texte"))
        self.file_name_label.setText(_translate("Steganographie", self.image_name))
        self.load_image_btn.setText(_translate("Steganographie", "Charger une image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Steganographie = QtWidgets.QDialog()
    ui = Ui_Steganographie()
    ui.setupUi(Steganographie)
    Steganographie.show()
    sys.exit(app.exec_())
