# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMainWindow,QMessageBox
from PIL import Image,ImageQt
from hidder import *

class Ui_Steganographie(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)
        self.image_name = "Aucune fichier selectionnée!"



    def load(self):
        try:
            dlg = QFileDialog()
            dlg.setFileMode(QFileDialog.AnyFile)
            filenames = ""

            if dlg.exec_():
                filenames = dlg.selectedFiles()
                print(filenames[0])
                self.file_name_label.setText(filenames[0])

            self.im = Image.open(filenames[0])
            self.output = "new_"+filenames[0].split("/")[-1]
            QtIm = ImageQt.ImageQt(self.im).copy()
            QtIm = QtGui.QImage(QtIm)
            pix = QtGui.QPixmap.fromImage(QtIm)
            self.image_container.setPixmap(pix)
            print(f"output is {self.output}")
        except Exception as e:
            QMessageBox.about(self,'Erreur',f"Essayez avec une autre fichier")
            self.reset()


    def reset(self):
        self.file_name_label.setText("Aucune fichier selectionnée!")
        self.image_container.clear()
        self.image_container.setText("(Vide)")
        self.text_container.clear()
        self.im = None
        self.keyContainer.clear()


    def hide(self):
        try:
            new_im = encode(self.text_container.toPlainText(),self.im,self.keyContainer.text())
            new_im.save(self.output)
            QMessageBox.about(self,'Title',f"Message cachée dans {self.output}\n Clé de cryptage: {self.keyContainer.text()}")
            self.reset()    
        except Exception as e:
            QMessageBox.about(self,'Erreur',f"Champ manquant")

        

    def show(self):
        try:
            QMessageBox.about(self ,"Contenue cachée",decode(self.im,self.keyContainer.text()))
        except Exception as e:
            QMessageBox.about(self,'Erreur',f"Champ manquant")

        self.reset()


    def setupUi(self, Steganographie):
        Steganographie.setObjectName("Steganographie")
        Steganographie.resize(282, 579)

        self.image_container = QtWidgets.QLabel(Steganographie)
        self.image_container.setGeometry(QtCore.QRect(20, 50, 250, 250))
        self.image_container.setAutoFillBackground(True)
        self.image_container.setAlignment(QtCore.Qt.AlignCenter)
        self.image_container.setObjectName("image_container")

        self.hide_text = QtWidgets.QPushButton(Steganographie)
        self.hide_text.setGeometry(QtCore.QRect(10, 540, 121, 31))
        self.hide_text.setObjectName("hide_text")
        self.hide_text.clicked.connect(self.hide)

        self.text_container = QtWidgets.QTextEdit(Steganographie)
        self.text_container.setGeometry(QtCore.QRect(10, 390, 261, 141))
        self.text_container.setObjectName("text_container")

        self.show_text = QtWidgets.QPushButton(Steganographie)
        self.show_text.setGeometry(QtCore.QRect(150, 540, 121, 31))
        self.show_text.setObjectName("show_text")
        self.show_text.clicked.connect(self.show)

        self.layoutWidget = QtWidgets.QWidget(Steganographie)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 261, 25))
        self.layoutWidget.setObjectName("layoutWidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.file_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.file_name_label.setObjectName("file_name_label")

        self.horizontalLayout.addWidget(self.file_name_label)

        self.load_image_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.load_image_btn.setObjectName("load_image_btn")
        self.load_image_btn.clicked.connect(self.load)
        self.horizontalLayout.addWidget(self.load_image_btn)

        self.label = QtWidgets.QLabel(Steganographie)
        self.label.setGeometry(QtCore.QRect(120, 370, 47, 13))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Steganographie)
        self.label_2.setGeometry(QtCore.QRect(100, 320, 91, 16))
        self.label_2.setObjectName("label_2")

        self.keyContainer = QtWidgets.QLineEdit(Steganographie)
        self.keyContainer.setGeometry(QtCore.QRect(10, 340, 261, 20))
        self.keyContainer.setObjectName("keyContainer")

        self.retranslateUi(Steganographie)
        QtCore.QMetaObject.connectSlotsByName(Steganographie)

    def retranslateUi(self, Steganographie):
        _translate = QtCore.QCoreApplication.translate
        Steganographie.setWindowTitle(_translate("Steganographie", "Steganography by Toavina"))
        self.image_container.setText(_translate("Steganographie", "Image"))
        self.hide_text.setText(_translate("Steganographie", "Cacher dans l\'image"))
        self.show_text.setText(_translate("Steganographie", "Extraire le texte"))
        self.file_name_label.setText(_translate("Steganographie", "Aucune fichier selectionnée"))
        self.load_image_btn.setText(_translate("Steganographie", "Charger une image"))
        self.label.setText(_translate("Steganographie", "Texte:"))
        self.label_2.setText(_translate("Steganographie", "Clé de cryptage:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Steganographie = QtWidgets.QDialog()
    ui = Ui_Steganographie()
    ui.setupUi(Steganographie)
    Steganographie.show()
    Steganographie.setObjectName("myParentWidget")
    Steganographie.setStyleSheet("QWidget#myParentWidget {background: #b3aff8}")
    app.processEvents()
    sys.exit(app.exec_())
